version: "3.8"
services:
  nordvpn:
    container_name: nordvpn
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN=${NORDTOKEN}
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=10.69.0.0/20  # So it can be accessed within the local network
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only