version: "3.8"
services:
  mkdocs:
    container_name: mkdocs
    image: squidfunk/mkdocs-material:latest
    volumes:
      - ./mkdocs:/docs
      - ./mkdocs/mkdocs.yml:/docs/mkdocs.yml
    ports:
      - 8000:8000
    command: [ "serve", "--dev-addr=0.0.0.0:8000" ]
    restart: unless-stopped