version: "3.8"
services:
  cloudflareddns:
    image: cr.hotio.dev/hotio/cloudflareddns
    container_name: cloudflareddns
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - INTERVAL=${INTERVAL}
      - DETECTION_MODE=${DETECTION_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - CF_APITOKEN=${CF_APITOKEN}
      - CF_RECORDTYPES=${CF_RECORDTYPES}
      - CF_HOSTS=${CF_HOSTS}
      - CF_ZONES=${CF_ZONES}
    volumes:
      - ./cloudflareddns/:/config
    restart: unless-stopped
