version: "3.8"
services:
  unpackerr:
    container_name: unpackerr
    image: ghcr.io/hotio/unpackerr
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    volumes:
      - ${DOCKERSTORAGEDIR}:/downloads
      - ${DOCKERCONFDIR}/unpackerr:/config
    ports:
      - 5656:5656
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=00775
      # Radarr Config
      - UN_RADARR_0_URL=https://radarr.i.readisright.com:443
      - UN_RADARR_0_API_KEY=${RADARR_API}
      - UN_RADARR_0_PATHS_0=/downloads/torrents/movies
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      # Sonarr Config
      - UN_SONARR_0_URL=https://sonarr.i.readisright.com:443
      - UN_SONARR_0_API_KEY=${SONARR_API}
      - UN_SONARR_0_PATHS_0=/downloads/torrents/tv
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Sonarr-Anime Config
      - UN_SONARR_1_URL=https://sonarr-anime.i.readisright.com:443
      - UN_SONARR_1_API_KEY=${SONARR_ANIME_API}
      - UN_SONARR_1_PATHS_1=/downloads/torrents/anime
      - UN_SONARR_1_PROTOCOLS=torrent
      - UN_SONARR_1_TIMEOUT=10s
      - UN_SONARR_1_DELETE_ORIG=false
      - UN_SONARR_1_DELETE_DELAY=5m
      # Lidarr Config
      - UN_LIDARR_0_URL=https://lidarr.i.readisright.com:443
      - UN_LIDARR_0_API_KEY=${LIDARR_API}
      - UN_LIDARR_0_PATHS_0=/downloads/torrents/music
      - UN_LIDARR_0_PROTOCOLS=torrent
      - UN_LIDARR_0_TIMEOUT=10s
      - UN_LIDARR_0_DELETE_ORIG=false
      - UN_LIDARR_0_DELETE_DELAY=5m
      # Readarr Config
      - UN_READARR_0_URL=https://readarr.i.readisright.com:443
      - UN_READARR_0_API_KEY=${READARR_API}
      - UN_READARR_0_PATHS_0=/downloads/torrents/books
      - UN_READARR_0_PROTOCOLS=torrent
      - UN_READARR_0_TIMEOUT=10s
      - UN_READARR_0_DELETE_ORIG=false
      - UN_READARR_0_DELETE_DELAY=5m
      # Readarr-Audio Config
      - UN_READARR_1_URL=https://readarr-audio.i.readisright.com:443
      - UN_READARR_1_API_KEY=${READARR_AUDIO_API}
      - UN_READARR_1_PATHS_1=/downloads/torrents/audiobooks
      - UN_READARR_1_PROTOCOLS=torrent
      - UN_READARR_1_TIMEOUT=10s
      - UN_READARR_1_DELETE_ORIG=false
      - UN_READARR_1_DELETE_DELAY=5m
    security_opt:
      - no-new-privileges:true