version: "3.8"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - ./dashy/public/conf.yml:/app/public/conf.yml
      - ./dashy/public/pages/:/app/public/pages/
      - ./dashy/public/item-icons/:/app/public/item-icons/
      - ./dashy/public/backgrounds/:/app/public/backgrounds/
      - ./dashy/src/styles/my-themes.scss:/app/src/styles/user-defined-themes.scss
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=1001
      - GID=1001
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s